MyStockTake/urls.py
from django.contrib import admin
from django.urls import path, include

from stocktake.views import (
    renderContact,
    renderIndex,
    renderPricing,
    renderAccount,
    renderRecipe,
    renderRecipePage,
    renderRecipeCreation,
    renderMyRecipes,
    renderRecipeEdit,
    renderRecipeDelete,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', renderIndex.as_view(), name='home'),
    path('pricing/', renderPricing, name='pricing'),
    path('contactus/', renderContact, name='contact'),
    path('user-account/', renderAccount, name='account'),
    path('all-recipes/',
         renderRecipe.as_view(), name='all_recipes'),
    path('recipes/<int:pk>/',
         renderRecipePage.as_view(), name='recipe_page'),
    path('my-recipes/',
         renderMyRecipes.as_view(), name='my_recipes'),
    path('recipes-creation/',
         renderRecipeCreation.as_view(),
         name='recipe_creation'),
    path('my-recipes/<int:pk>/edit',
         renderRecipeEdit.as_view(),
         name='recipe_edit'),
    path('my-recipes/<int:pk>/delete',
         renderRecipeDelete.as_view(), name='delete_recipe'),
    path('accounts/',
         include('allauth.urls'), name='accounts_urls'),
]

stocktake/urls.py
from . import views
from django.urls import path

urlPatterns = [
    path('', views.renderIndex.as_view(), name='home'),
    path('/pricing/', views.renderPricing, name='pricing'),
    path('/contact/', views.renderContact, name='contact'),
    path('/user-account/', views.renderAccount, name='account'),
    path('/all-recipes/', views.renderRecipe.as_view(), name='all_recipes'),
    path('/recipes/<int:pk>/',
         views.renderRecipePage.as_view(), name='recipe_page'),
    path('/my-recipes/', views.renderMyRecipes.as_view(), name='my_recipes'),
    path('/recipes-creation/', views.renderRecipeCreation.as_view(),
         name='recipe_creation'),
    path('/my-recipes/<int:pk>/edit',
         views.renderRecipeEdit.as_view(), name='recipe_edit'),
    path('/my-recipes/<int:pk>/delete',
         views.renderRecipeDelete.as_view(), name='delete_recipe'),
]

stocktake/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse
from ckeditor.fields import RichTextField

STATUS = ((0, 'Draft'), (1, 'Published'))


class Recipes(models.Model):
    """
    The main recipe model to build the database. Which is then split
    out to each page that renders the recipe.
    """
    title = models.CharField(max_length=30)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipe_post')
    recipe_desc = models.CharField(max_length=150, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    ingredients_list = RichTextField(blank=True, null=True)
    methods_list = RichTextField(blank=True, null=True)
    recipe_story = RichTextField(blank=True, null=True)
    status = models.IntegerField(choices=STATUS, default=1)
    featured_image = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('home')

stocktake/forms.py
from django import forms
from .models import Recipes


class createRecipe(forms.ModelForm):

    class Meta:
        model = Recipes
        fields = ('title',  'author', 'recipe_desc', 'recipe_story',
                  'ingredients_list', 'methods_list', 'featured_image')

        widgets = {

            'title': forms.TextInput(attrs={'class': 'form-control', 'id': 'recipe-title form4Example3', 'rows': '4'}),
            'author': forms.HiddenInput(attrs={'class': 'form-control', 'placeholder': '', 'id': 'author_id', 'value': ''}),
            'recipe_desc': forms.TextInput(attrs={'class': 'form-control'}),
            'recipe_story': forms.Textarea(attrs={'class': 'form-control'}),
            'ingredients_list': forms.Textarea(attrs={'class': 'form-control'}),
            'methods_list': forms.Textarea(attrs={'class': 'form-control'}),
            'featured_image': forms.FileInput(attrs={'class': 'form-control'})
        }

stocktake/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Recipes
from .forms import createRecipe
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.

"""
Simple return render requests for templates/pages that dont need any 
other logic for them to be used by the application or user.
"""


def renderContact(request):
    return render(request, 'contactus.html', {})


def renderLogin(request):
    return render(request, 'login.html', {})


def renderPricing(request):
    return render(request, 'pricing.html', {})


def renderAccount(request):
    return render(request, 'useraccount.html', {})


"""
Class based views that contain more logic that is 
required from the database.
"""


class renderRecipeCreation(generic.CreateView):

    model = Recipes
    form_class = createRecipe
    template_name = 'recipe_create.html'

    def form_valid(self, form_class):

        if form_class.is_valid():
            form_class.save()
            messages.success(self.request, 'Recipe created successfully')
            return redirect('home')


class renderIndex(generic.ListView):

    model = Recipes
    queryset = Recipes.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 3


class renderRecipe(generic.ListView):

    model = Recipes
    queryset = Recipes.objects.filter(status=1).order_by('-created_on')
    template_name = 'recipe.html'
    paginate_by = 6


class renderRecipePage(generic.DetailView):

    model = Recipes
    template_name = 'recipe_page.html'


class renderMyRecipes(generic.ListView):

    model = Recipes
    queryset = Recipes.objects.filter(status=1).order_by('-created_on')
    template_name = 'my_recipes.html'
    paginate_by = 9


class renderRecipeEdit(generic.UpdateView):

    model = Recipes
    template_name = 'recipe_edit.html'
    form_class = createRecipe

    def form_valid(self, form_class):

        if form_class.is_valid():
            form_class.save()
            messages.info(self.request, 'Recipe Edited successfully')
            return redirect('home')


class renderRecipeDelete(generic.DeleteView):

    model = Recipes
    template_name = 'recipe_delete.html'
    success_url = reverse_lazy('my_recipes')
    form_class = createRecipe
    success_message = "Recipe Deleted successfully"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6ab0a7bbf9.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
    <link rel="icon" type="image/x-icon" href="{% static 'media/favicon.ico' %}">
    <script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js">
    </script>
    
    <!-- Function to send the user contact form email using the emailjs system -->
    <script type="text/javascript">
        (function(){
            emailjs.init("_LzmMaNXFCJQpzF9b")
        })();
    </script>
    <title>myRecipe</title>
</head>
<body>
    <!-- Navigation code blocks -->
        {% if user.is_authenticated %}
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand main-title" href="{% url 'home' %}">|myRecipe</a>
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse pt-4 navbar-main pe-3" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_recipes' %}">Recipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account' %}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}"><i class="fa-regular fa-user fa-lg"></i> Logout</a>
                </li>
                </ul>
            </div>
            <div class="user-main">
                <p>Welcome <strong>{{ user.username }}</strong></p>
            </div>
            </div>
        </nav>
        {% else %}
        <!-- For users that are not registered to the application -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">code|myRecipe</a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}"><i class="fa-regular fa-user fa-lg"></i> Login</a>
            </li>
            </ul>
        </div>
        </div>
    </nav>
    {% endif %}
    <!-- General page code blocks  -->
        {% block content %}
        <!-- Based on the various pages of the application it depends what content is displayed here -->
        {% if user.is_authenticated %}

        {% else %}

        {% endif %}

        {% endblock content %}
    <!-- Footer code blocks  -->
    {% if user.is_authenticated %}
    
    {% else %}
    <footer class="bg-primary text-white text-center text-lg-start">
        <div class="container p-4">
          <div class="row">
            <div class="col-lg-5 col-md-12 mb-4 mb-md-0">
              <p class="pt-3">
                The myRecipe platform is designed to stream line your recipe and menu creation process.
                By providing the tools to make your recipe's, we aim to make this dreaded task an enjoyable one. 
              </p>
            </div>
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            </div>
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0 pt-4 ps-5">
              <a href="{% url 'contact' %}" aria-label="Opens the contact form page of the application"><button class="btn btn-rounded btn-light text-uppercase mb-0 text-center fs-6">Contact Us</button></a>
            </div>
          </div>
        </div>
    </div>
    {% endif %}
        <div class="f-bg text-center p-2">
            &copy  <script>document.write(new Date().getFullYear())</script> myRecipe |  Kyle Chart |  <a target="_blank" aria-label="Opens up Kyle Charts github" href="https://www.github.com/mrekyle"><i class="fa-brands fa-github git-link ps-2"></i></a>
        </div>
    </footer>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/email.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/alerts.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
<div class="container header-alert">
  <div class="row pt-5 mt-5">
      <div class="col-md-8 offset-md-2">
          {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dissable fade show" id="msg" role="alert">
                  {{ message | safe }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close Alert"></button> 
              </div>
          {% endfor %}
      </div>
  </div>
</div>
<div class="container index-header header-size">
    <div class="row">
        <div class="text-center">
            <h3>Get Started</h3>
            <p class="ps-5 col-md-5 mt-4 mb-4">Get started by clicking on the <strong>New Recipe</strong> button below and fill out all the information on the next page 
                to create your very first Recipe.<br> If you wish to edit or delete them, click on the edit button. <br>Which will take you there.<br>
                To view all of your recipes you have created, click on the <strong>My Recipe's</strong> button.
            </p>
        </div>
    </div>
    <hr>
    <!-- Authenticated user navigation for creating and editing recipes -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <div class="container-fluid">
            <div class="justify-content-center">
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarCenteredExample" aria-controls="navbarCenteredExample"
                    aria-expanded="false" aria-label="Toggle navigation"><i class="fas fa-bars"></i></button>
            </div>
          <div
            class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample" >
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'my_recipes' %}">My Recipe's</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipe_creation' %}">Create New Recipe</a>
            </ul>
        </div>
    </nav>
    <!-- Latest recipes added to the application  -->
        <h3 class="mb-3 pt-4 text-center underline">The Latest Recipe's</h3>
        <div class="container-fluid ms-4">
        <div class="row">
            <div class="col-12 mt-3 left">
                <div class="row d-flex justify-content-center">
                    <!-- Latest Recipe Cards -->
                    {% for Recipes in recipes_list %}
                        <div class="col-md-4">
                            <div class="card card-size mb-4 hover-shadow .shadow-6">
                                <div class="card-body">
                                      <a href="{% url 'recipe_page' Recipes.pk %}" aria-label="Opens the recipe in a full screen view" class="card-link">
                                        <div class="image-container masthead-text masthead-image">
                                          {% if 'placeholder' in Recipes.featured_image.url %}
                                            <img class="card-img indx-img" src="https://res.cloudinary.com/dcjikvzf6/image/upload/v1692107043/cld-sample-4.jpg" alt="Recipe Image">
                                          {% else %}
                                            <img class="card-img indx-img" src="{{ Recipes.featured_image.url }}" alt="Users image of there recipe">
                                          {% endif %}
                                        </div>
                                        <div class="">
                                          <h4 class="card-title text-center pt-1">{{ Recipes.title }}</h4>
                                        </div>
                                      </a>
                                         <div class="text-muted text-center recipe-subtitle">
                                            {{ Recipes.recipe_desc | safe }}
                                        </div>
                                        <div class="">
                                          <hr>
                                            <small><p class="card-text text-muted">Author: {{ Recipes.author }} |  {{ Recipes.created_on }}</p></small>
                                        </div>
                                  </div>
                            </div>
                        </div>
                    {% if forloop.counter|divisibleby:3 %}
                </div>
                <div class="row">
                    {% endif %}
                    
                    {% endfor %} 
                </div>
            </div>
        </div>
        {% if is_paginated %}
      {% endif %}
    </div>
</div>
<!-- If the user isn't authenticated  -->
{% else %}
<div class="container header-alert">
  <div class="row pt-5 mt-5">
      <div class="col-md-8 offset-md-2">
          {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dissable fade show" id="msg" role="alert">
                  {{ message | safe }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close Alert"></button> 
              </div>
          {% endfor %}
      </div>
  </div>
</div>
    <div class="container header-size">
        <div class="index-slider mb-4">
            <!-- Carousel wrapper -->
<div id="carouselBasicExample" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <!-- Indicators -->
    <div class="carousel-indicators">
      <button
        type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button> 
      <button type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide-to="2" aria-label="Slide 3"></button>
    </div>
  
    <!-- Inner -->
    <div class="carousel-inner">
      <!-- Single item -->
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dcjikvzf6/image/upload/v1695570889/my-recipe/static/media/user-home.0b73463215fc.png" class="img-size d-block w-100" alt=" Users home page"/>
      </div>
  
      <!-- Single item -->
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dcjikvzf6/image/upload/v1695570884/my-recipe/static/media/recipe.d1f086f53e19.png" class="img-size d-block w-100" alt="Recipe in full screen"/>
      </div>
  
      <!-- Single item -->
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dcjikvzf6/image/upload/v1695570881/my-recipe/static/media/allrecipe.a6a77cde6d8b.png" class="img-size d-block w-100" alt="All Recipes view"/>

      </div>
    </div>
    <!-- Inner -->
  
    <!-- Controls -->
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <!-- Carousel wrapper -->
        </div>
    </div>
    <div class="container pt-4 mt-4">
        <hr>
    </div>
    <div>
        <div class="container mt-4 mb-5 index-text">
            <div class="row text-center">
                <div>
                    <p>Are you looking for a way to create new menu's for that dinner party you've been planning? 
                        Where you can get a shopping list generated for everything you need? Worried about the allergies 
                        of friends and family?
                    </p>
                </div>
                <div>
                    <p>Here at myRecipe we have all the tools you could ever need to plan that perfect menu. We even allow you to see other 
                        recipe's created by our dedicated users. From Restaurant Professionals to the everyday home cook. 
                        We have everything you could ever need.
                    </p>
                </div>
                <div>
                    <p>
                        With new features currently being built and coming soon to our platform, we are also constantly updating our platform. 
                        Please take a look at what we currently offer and see if we are right for you!
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/my_recipes.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

<div class="container-fluid header-size pt-5">
    <div class="row">
        <h1 class="ms-2 my-recipe-title">Your Recipes</h1>
        <!-- Quick start to create a recipe  -->
        <div class="create-recipe pe-5 text-end">
            <p>No recipe's appearing? Click <button type="button" data-mdb-ripple-color="dark" class="btn btn-update ps-2 pe-2 ms-1 me-1"> <a href="{% url 'recipe_creation' %}" aria-label="Opens the create a recipe page">Here</a> </button>to get started</p>
        </div>
        <div class="text-center mb-3 mt-3">
            <h4 class="mb-3">Welcome - <strong>{{ user.username }}</strong></h4>
            <p>Here you can find all of your own recipe's that you have created and uploaded to the platform.<br>
            If you wish to make an edit or delete a recipe please select that button from the cards and follow the next steps</p>
        </div>
    </div>
    <div class="container text-center ms-4 mt-5">
        <div class="row">
            <div class="col-12 mt-1">
                <div class="row">
                    {% for Recipes in recipes_list %}
                        {% if user.id == Recipes.author.id %}
                            <div class="col-md-4">
                                <!-- Users own created recipe cards  -->
                                <div class="card ms-5 edit-card mb-4 hover-shadow .shadow-6">
                                    <div class="card-body">
                                        <a href="{% url 'recipe_page' Recipes.pk %}" aria-label="Opens the recipe in a full screen view" class="card-link">
                                            <div class="image-container masthead-text masthead-image">
                                            {% if 'placeholder' in Recipes.featured_image.url %}
                                                <img class="card-img card-image-myrcp" src="https://res.cloudinary.com/dcjikvzf6/image/upload/v1692107043/cld-sample-4.jpg" alt="Recipe Image">
                                            {% else %}
                                                <img class="card-img card-image-myrcp" src="{{ Recipes.featured_image.url }}" alt="Users image of there recipe">
                                            {% endif %}
                                            </div>
                                            <div class="">
                                            <h4 class="card-title text-center pt-2">{{ Recipes.title }}</h4>
                                            </div>
                                        </a>
                                        <hr>
                                        <div class="card-text text-center flex-container">
                                            <button class="ps-2 pe-2 pb-2 pt-2 btn btn-edit" type="button"><a href="{% url 'recipe_edit' Recipes.pk %}" aria-label="Opens the edit recipe page">Edit</a></button>
                                            <button class='ps-2 pe-2 pb-2 pt-2 btn btn-delete' type="button"><a href="{% url 'delete_recipe' Recipes.pk %}" aria-label="Opens the delete recipe page">Delete</a></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            </div>
                            <div class="row mb-1">
                        {% endif %}
                    
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if is_paginated %}
        <div class="container">
            <hr>
        </div>
      <nav  aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li>
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
          </li>
          {% endif %} 
          {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
    <div class="container-main mb-4"></div>
</div>

{% else %}
    <div class="container header-size text-center">
        <h3>Unfortunately we do not know you! But we'd love to get to know you. So please join us on our adventure.</h3>
        <h3>Please click below to check out what we offer, to see if you want to join us.</h3>
        <a href="{% url 'pricing' %}" aria-label="Opens the Pricing page to allow the user to see what we offer"><button class="btn btn-rounded mb-5 btn-dark">What We Offer</button></a>
    </div>
{% endif %}
{% endblock %}

templates/recipe.html
{% extends "base.html" %}
{% block content%}

{% if user.is_authenticated %}
<div class="container-fluid header-size ms-4">
  <div class="page-title">
    <h1 class="pt-3 mb-4">Our Recipes</h1>
  </div>
    <div class="row mt-4 mb-10">
        <div class="col-12 mt-3 left">
            <div class="row d-flex justify-content-center">
              <!-- Recipe card - Displaying multiple cards paginated -->
                {% for Recipes in recipes_list %}
                    <div class="col-md-3">
                      <div class="card card-size-recipe mb-4 hover-shadow .shadow-6">
                            <div class="card-body">
                                  <a href="{% url 'recipe_page' Recipes.pk %}" aria-label="Opens the recipe in a full screen view" class="card-link">
                                    <div class="image-container masthead-text masthead-image">
                                      {% if 'placeholder' in Recipes.featured_image.url %}
                                        <img class="card-img card-image" src="https://res.cloudinary.com/dcjikvzf6/image/upload/v1692107043/cld-sample-4.jpg" alt="Recipe Image">
                                      {% else %}
                                        <img class="card-img card-image" src="{{ Recipes.featured_image.url }}" alt="Users image of there recipe">
                                      {% endif %}
                                    </div>
                                    <div class="">
                                      <h4 class="card-title text-center pt-1">{{ Recipes.title }}</h4>
                                    </div>
                                  </a>
                                     <div class="text-muted text-center recipe-subtitle">
                                        {{ Recipes.recipe_desc | safe }}
                                    </div>
                                    <div class="">
                                      <hr>
                                        <p class="card-text text-muted">Author: {{ Recipes.author }} |  {{ Recipes.created_on }}</p>
                                    </div>
                              </div>
                      </div>
                    </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
          <div class="row d-flex justify-content-center">
                {% endif %}
                
                {% endfor %} 
            </div>
        </div>
    </div>

    <!-- Page navigation if the page is required to be paginated  -->
    {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mb-4">
      {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
      </li>
      {% endif %} 
      {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% else %}
  <!-- If the user is'nt authenticated as part of the application. Render this  -->
  <div class="container header-size text-center">
      <h3>Unfortunately we do not know you! But we'd love to get to know you. So please join us on our adventure.</h3>
      <h3>Please click below to check out what we offer, to see if you want to join us.</h3>
      <a href="{% url 'pricing' %}" aria-label="Opens the Pricing page to allow the user to see what we offer"><button class="btn btn-rounded mb-5 btn-dark">What We Offer</button></a>
  </div>
{% endif %}

{% endblock %}